name: meme-gan
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: run pipe
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global --add safe.directory /__w/MEME-GAN/MEME-GAN
            pip install -r require.txt
            dvc repro
            
            echo "## img gan" > report.md
            cat img-metrics.txt >> report.md
            cml publish imgGAN.png --md >> report.md
            
            echo "## text gan" > report.md
            cat text-metrics.txt >> report.md
            cml publish textGAN.png --md >> report.md
            
            echo "## memeify" >> report.md
            cml publish memes/meme1.png --md >> report.md
            
            cml send-comment report.md
            
